package(default_visibility = ['//visibility:public'])

alias(
    name = "binaries",
    actual = "@emscripten_bin_linux//:all",
)

alias(
    name = "node_modules",
    actual = "@emscripten_npm_linux//:node_modules",
)

