language: python

services:
  - docker

before_install:
  - docker pull ubuntu:16.04

install:
  - pip install flake8==3.8.7

script:
  - flake8
  - set -o errexit
  - echo "running..."
  - docker build .

notifications:
  email: false
