sudo: required

language: python

services:
  - docker

before_install:
  - docker pull ubuntu:16.04

script:
  - set -o errexit
  - echo "running..."
  - docker build --build-arg TEST_TARGET="$TEST_TARGET" .

notifications:
  email: false
