on:
  create:
    tags:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  flake8:
    name: flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install flake8==3.7.8
      - run: python3 -m flake8 --show-source --statistics
      - name: install python2 pip
        run: sudo apt-get install -q -y python2 python-pip
      - run: python2 -m pip install flake8==3.7.8
      - run: python2 -m flake8 --show-source --statistics
